name: instalog_android
description: Android implementation of the Instalog plugin that integrates with the native Android SDK for analytics, logs, and feedback.
version: 0.1.2
homepage: https://instalog.dev
repository: https://github.com/instalog-dev/instalog-flutter

resolution: workspace
environment:
  sdk: "^3.6.0"
  flutter: '>=3.3.0'

flutter:
  plugin:
    implements: instalog_flutter
    platforms:
      android:
        package: dev.instalog.flutter
        pluginClass: InstalogPlugin
        dartPluginClass: InstalogAndroid

dependencies:
  flutter:
    sdk: flutter
  instalog_platform_interface: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  flutter_lints: ^5.0.0
