name: instalog_flutter
description: Flutter plugin for Instalog analytics, logging, error tracking, and user feedback collection services.
version: 0.1.0
homepage: https://instalog.dev
repository: https://github.com/instalog-dev/instalog-flutter

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dev_dependencies:
  melos: 4.1.0