name: instalog_platform_interface
description: Platform interface for the Instalog plugin providing a common API for all platform implementations.
version: 0.1.0+1
publish_to: none
homepage: https://instalog.dev
repository: https://github.com/instalog-dev/instalog-flutter

environment:
  sdk: "^3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
