name: instalog_flutter
description: Flutter plugin for Instalog analytics, logging, error tracking, and user feedback collection services.
version: 0.1.1
homepage: https://instalog.dev
repository: https://github.com/instalog-dev/instalog-flutter

resolution: workspace
environment:
  sdk: "^3.6.0"
  flutter: '>=3.3.0'

flutter:
  plugin:
    platforms:
      android:
        default_package: instalog_android
      ios:
        default_package: instalog_ios

dependencies:
  flutter:
    sdk: flutter
  instalog_android: ^0.1.1
  instalog_ios: ^0.1.1
  instalog_platform_interface: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  plugin_platform_interface: ^2.1.8
  flutter_lints: ^5.0.0
