name: instalog
description: Flutter plugin for Instalog analytics, logging, error tracking, and user feedback collection services.
version: 0.1.0+1
publish_to: none
homepage: https://instalog.dev
repository: https://github.com/instalog-dev/instalog-flutter

environment:
  sdk: "^3.3.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: instalog_android
      ios:
        default_package: instalog_ios

dependencies:
  flutter:
    sdk: flutter
  instalog_android:
    path: ../instalog_android
  instalog_ios:
    path: ../instalog_ios
  instalog_platform_interface:
    path: ../instalog_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  plugin_platform_interface: ^2.1.8
  flutter_lints: ^5.0.0
