name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          if [[ ! $PR_TITLE =~ ^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?: ]]; then
            echo "PR title '$PR_TITLE' does not follow conventional commit format"
            echo "Expected format: type(scope): description"
            echo "Valid types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert"
            exit 1
          fi
