name: instalog

on:
  pull_request:
    paths:
      - ".github/workflows/instalog.yaml"
      - "instalog/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/instalog.yaml"
      - "instalog/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: instalog
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test --coverage
      - name: Check code formatting
        run: dart format --set-exit-if-changed .

  ios:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: instalog/example
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Build iOS
        run: flutter build ios --release
