name: instalog_platform_interface

on:
  pull_request:
    paths:
      - ".github/workflows/instalog_platform_interface.yaml"
      - "instalog_platform_interface/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/instalog_platform_interface.yaml"
      - "instalog_platform_interface/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: instalog_platform_interface
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test
      - name: Check code formatting
        run: dart format --set-exit-if-changed .

